apiVersion: v1
kind: Service
metadata:
  labels:
    app: cadvisor-svc
    release: opc-prom
  name: opc-prom-cadvisor-svc
  namespace: monitoring
  selfLink: /api/v1/namespaces/monitoring/services/opc-prom-cadvisor-svc
spec:
  ports:
  - name: chttp
    port: 9002
    protocol: TCP
    targetPort: 8080
  selector:
    app: cadvisor
    name: cadvisor
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
