---

####################
# MongoDB Configuration
####################

- hosts: localhost
  tasks:
    - name: Configure mongoDB
      shell : /root/k8s-mongodb/tasks/mongo-bootstrap.sh 3
      register: cmd_result
    - debug: msg={{cmd_result.stdout}}

