---

####################
# MongoDB Configuration
####################

- hosts: localhost
  tasks:
    - name: Configure mongoDB
      shell : /root/k8s-mongodb/templates/mongo-bootstrap.sh 3
      register: cmd_result

