---

####################
# Prometheus Configuration
####################

- hosts: localhost
  tasks:
    - name: Configure prometheus
      shell : /root/k8s-mongodb/tasks/prometheus-setup.sh
      args:
        executable: /bin/bash
      register: cmd_result


