---

####################
# Create Kubernetes cluster using Kops
####################

- hosts: localhost
  tasks:
    - name: Configure prometheus
      shell : /k8s-mongodb/templates/prometheus-setup.sh
      args:
        executable: /bin/bash
      register: cmd_result

    - name: Configure MongoDB exporter and Cadvisor
      shell : /k8s-mongodb/templates/exporters-setup.sh
      args:
        executable: /bin/bash
      register: cmd_result 

